//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satisfaction
    {
        public int id { get; set; }
        public Nullable<int> desk { get; set; }
        public string date { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public string numPeople { get; set; }
        public string idx { get; set; }
        public Nullable<int> numSatisfactory { get; set; }
        public Nullable<int> numUnsatisfactory { get; set; }
        public Nullable<int> numMedium { get; set; }
    }
}
